AWSTemplateFormatVersion: "2010-09-09"
Description: Lambdas + IAM + event source mappings (SQS -> Ingress/Builder, Kinesis -> Processor).

Parameters:
  ArtifactBucket: { Type: String }
  IngressLambdaS3Key: { Type: String }
  TelematicsProcessorLambdaS3Key: { Type: String }
  TripSummaryBuilderLambdaS3Key: { Type: String }
  TripSummaryApiLambdaS3Key: { Type: String }

  IngressQueueArn: { Type: String }
  IngressQueueUrl: { Type: String }
  TripSummaryQueueArn: { Type: String }
  TripSummaryQueueUrl: { Type: String }
  IngressStreamArn: { Type: String }
  IngressStreamName: { Type: String }

  TelemetryEventsTableName: { Type: String }
  TripsTableName: { Type: String }
  TripSummaryTableName: { Type: String }
  PslCacheTableName: { Type: String }
  OverspeedDedupeTableName: { Type: String }
  VehicleStateTableName: { Type: String }
  VehicleRegistryTableName: { Type: String }
  FleetRegistryTableName: { Type: String }
  CustomerFleetMapTableName: { Type: String }
  CustomerRegistryTableName: { Type: String }

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: [lambda.amazonaws.com] }
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: onpoint-runtime-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:BatchWriteItem
                Resource: "*"
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                  - kinesis:DescribeStreamSummary
                  - kinesis:ListShards
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                  - sqs:SendMessage
                Resource: "*"

  IngressLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-ingress
      Runtime: python3.12
      Handler: onpoint_dev_ingress.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref IngressLambdaS3Key
      Environment:
        Variables:
          INGRESS_STREAM_NAME: !Ref IngressStreamName

  IngressEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref IngressQueueArn
      FunctionName: !Ref IngressLambda
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 2
      Enabled: true

  TelematicsProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-telematics-processor
      Runtime: python3.12
      Handler: telematics_processor.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 512
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TelematicsProcessorLambdaS3Key
      Environment:
        Variables:
          TELEMETRY_EVENTS_TABLE: !Ref TelemetryEventsTableName
          TRIPS_TABLE: !Ref TripsTableName
          PSL_CACHE_TABLE: !Ref PslCacheTableName
          OVERSPEED_DEDUPE_TABLE: !Ref OverspeedDedupeTableName
          VEHICLE_STATE_TABLE: !Ref VehicleStateTableName
          VEHICLE_REGISTRY_TABLE: !Ref VehicleRegistryTableName
          FLEET_REGISTRY_TABLE: !Ref FleetRegistryTableName
          CUSTOMER_FLEET_MAP_TABLE: !Ref CustomerFleetMapTableName
          CUSTOMER_REGISTRY_TABLE: !Ref CustomerRegistryTableName
          TRIP_SUMMARY_QUEUE_URL: !Ref TripSummaryQueueUrl

  ProcessorEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref IngressStreamArn
      FunctionName: !Ref TelematicsProcessorLambda
      StartingPosition: LATEST
      BatchSize: 100
      MaximumBatchingWindowInSeconds: 2
      Enabled: true

  TripSummaryBuilderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-trip-summary-builder
      Runtime: python3.12
      Handler: trip_summary_builder.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 120
      MemorySize: 512
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TripSummaryBuilderLambdaS3Key
      Environment:
        Variables:
          TELEMETRY_EVENTS_TABLE: !Ref TelemetryEventsTableName
          TRIP_SUMMARY_TABLE: !Ref TripSummaryTableName

  TripSummaryBuilderEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref TripSummaryQueueArn
      FunctionName: !Ref TripSummaryBuilderLambda
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 5
      Enabled: true

  TripSummaryApiLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-trip-summary-api
      Runtime: python3.11
      Handler: trip_summary_api.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TripSummaryApiLambdaS3Key
      Environment:
        Variables:
          TRIP_SUMMARY_TABLE: !Ref TripSummaryTableName
          DEFAULT_LIMIT: "50"
          MAX_LIMIT: "200"
          PAGE_SIZE: "100"
          MAX_PAGES_PER_VIN: "3"

Outputs:
  TripSummaryApiLambdaArn:
    Value: !GetAtt TripSummaryApiLambda.Arn
