AWSTemplateFormatVersion: "2010-09-09"
Description: >
  OnPointAI DynamoDB tables (clean recreate, on-demand, AWS-managed KMS, no GSIs).
  TTL enabled for telemetry-events + psl-cache + overspeed-dedupe + geofence-events using attribute "expiresAt".
  NOTE: Your app must write "expiresAt" as epoch seconds.

Parameters:
  TelemetryEventsTableName:
    Type: String
    Default: onpoint-dev-telemetry-events

  TripSummaryTableName:
    Type: String
    Default: onpoint-dev-trip-summary

  TripsTableName:
    Type: String
    Default: onpoint-dev-trips

  PslCacheTableName:
    Type: String
    Default: onpoint-dev-psl-cache

  OverspeedDedupeTableName:
    Type: String
    Default: onpoint-dev-overspeed-dedupe

  VehicleStateTableName:
    Type: String
    Default: onpoint-dev-vehicle-state

  VehicleRegistryTableName:
    Type: String
    Default: dev-vehicle-registry

  # --------------------------
  # Customer registry (NEW)
  # --------------------------
  CustomerRegistryTableName:
    Type: String
    Default: onpoint-dev-customer-registry

  # --------------------------
  # Fleet registry (NEW)
  # --------------------------
  FleetRegistryTableName:
    Type: String
    Default: onpoint-dev-fleet-registry

  # --------------------------
  # Customer ↔ Fleet mapping (NEW)
  # --------------------------
  CustomerFleetMapTableName:
    Type: String
    Default: onpoint-dev-customer-fleet-map

  # --------------------------
  # Geo-fence tables (NEW)
  # --------------------------
  GeoFenceDefinitionsTableName:
    Type: String
    Default: onpoint-dev-geofence-definitions

  GeoFenceAssignmentsTableName:
    Type: String
    Default: onpoint-dev-geofence-assignments

  GeoFenceStateTableName:
    Type: String
    Default: onpoint-dev-geofence-state

  GeoFenceEventsTableName:
    Type: String
    Default: onpoint-dev-geofence-events

  DynamoAwsManagedKmsKeyId:
    Type: String
    Default: alias/aws/dynamodb
    Description: AWS-managed KMS key for DynamoDB

Resources:
  TelemetryEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TelemetryEventsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  TripSummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TripSummaryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL intentionally NOT enabled (per your requirement)

  TripsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TripsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId

  PslCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PslCacheTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  OverspeedDedupeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref OverspeedDedupeTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  VehicleStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref VehicleStateTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId

  VehicleRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref VehicleRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId

  # ============================================================
  # Customer registry (NEW)
  # ============================================================
  CustomerRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CustomerRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off: registry/config/master data

  # ============================================================
  # Fleet registry (NEW)
  # ============================================================
  FleetRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FleetRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off: registry/config data

  # ============================================================
  # Customer ↔ Fleet mapping (NEW)
  # ============================================================
  CustomerFleetMapTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CustomerFleetMapTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off: mapping data

  # ============================================================
  # Geo-fence tables (NEW)
  # ============================================================
  GeoFenceDefinitionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceDefinitionsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off: configuration data

  GeoFenceAssignmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceAssignmentsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off: configuration mappings

  GeoFenceStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceStateTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      # TTL off by default (small bounded state).
      # If you later want: enable TTL with expiresAt.

  GeoFenceEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceEventsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

Outputs:
  TelemetryEventsTableNameOut:
    Value: !Ref TelemetryEventsTableName
  TripSummaryTableNameOut:
    Value: !Ref TripSummaryTableName
  TripsTableNameOut:
    Value: !Ref TripsTableName
  PslCacheTableNameOut:
    Value: !Ref PslCacheTableName
  OverspeedDedupeTableNameOut:
    Value: !Ref OverspeedDedupeTableName
  VehicleStateTableNameOut:
    Value: !Ref VehicleStateTableName
  VehicleRegistryTableNameOut:
    Value: !Ref VehicleRegistryTableName

  CustomerRegistryTableNameOut:
    Value: !Ref CustomerRegistryTableName

  FleetRegistryTableNameOut:
    Value: !Ref FleetRegistryTableName
  CustomerFleetMapTableNameOut:
    Value: !Ref CustomerFleetMapTableName

  GeoFenceDefinitionsTableNameOut:
    Value: !Ref GeoFenceDefinitionsTableName
  GeoFenceAssignmentsTableNameOut:
    Value: !Ref GeoFenceAssignmentsTableName
  GeoFenceStateTableNameOut:
    Value: !Ref GeoFenceStateTableName
  GeoFenceEventsTableNameOut:
    Value: !Ref GeoFenceEventsTableName