AWSTemplateFormatVersion: "2010-09-09"
Description: onpoint root stack

Parameters:
  Env:
    Type: String
    Default: dev
  ProjectName:
    Type: String
    Default: onpoint
  TemplateBucket:
    Type: String
  TemplatePrefix:
    Type: String
  TemplateVersion:
    Type: String
    Default: v1
  EnableTenantFleetIndex:
    Type: String
    Default: "false"
  UserPoolId:
    Type: String
    Default: ""
  IngressCodeS3Key:
    Type: String
    Default: lambda/ingress.zip
  TelematicsProcessorCodeS3Key:
    Type: String
    Default: lambda/telematics_processor.zip
  PslEnricherCodeS3Key:
    Type: String
    Default: lambda/psl_enricher.zip
  OverspeedDetectorCodeS3Key:
    Type: String
    Default: lambda/overspeed_detector.zip
  TripSummaryBuilderCodeS3Key:
    Type: String
    Default: lambda/trip_summary_builder.zip
  TripSummaryApiCodeS3Key:
    Type: String
    Default: lambda/trip_summary_api.zip
  VehicleStateApiCodeS3Key:
    Type: String
    Default: lambda/vehicle_state_api.zip
  FleetTenancyApiCodeS3Key:
    Type: String
    Default: lambda/fleet_tenancy_api.zip
  CommonLayerS3Key:
    Type: String
    Default: lambda/onpoint_common_layer.zip
  EnableUiStack:
    Type: String
    Default: "false"
  UiBucketName:
    Type: String
    Default: ""
  UiPriceClass:
    Type: String
    Default: PriceClass_100
  UiCustomDomainName:
    Type: String
    Default: ""
  UiAcmCertificateArn:
    Type: String
    Default: ""
  UiHostedZoneId:
    Type: String
    Default: ""

Conditions:
  UseProvidedUserPoolId: !Not [!Equals [!Ref UserPoolId, ""]]
  UseProvidedUiBucketName: !Not [!Equals [!Ref UiBucketName, ""]]
  EnableUiStackCondition: !Equals [!Ref EnableUiStack, "true"]

Resources:
  StreamsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/streams.yaml

  QueuesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/queues.yaml

  TablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        EnableTenantFleetIndex: !Ref EnableTenantFleetIndex
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/tables.yaml

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/cognito.yaml

  LambdasStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        TelematicsStreamName: !GetAtt StreamsStack.Outputs.TelematicsStreamName
        TelematicsStreamArn: !GetAtt StreamsStack.Outputs.TelematicsStreamArn
        IngressQueueArn: !GetAtt QueuesStack.Outputs.IngressQueueArn
        PslEnrichQueueUrl: !GetAtt QueuesStack.Outputs.PslEnrichQueueUrl
        PslEnrichQueueArn: !GetAtt QueuesStack.Outputs.PslEnrichQueueArn
        TripSummaryQueueUrl: !GetAtt QueuesStack.Outputs.TripSummaryQueueUrl
        TripSummaryQueueArn: !GetAtt QueuesStack.Outputs.TripSummaryQueueArn
        TelemetryEventsTableName: !GetAtt TablesStack.Outputs.TelemetryEventsTableName
        VinRegistryTableName: !GetAtt TablesStack.Outputs.VinRegistryTableName
        TenantsTableName: !GetAtt TablesStack.Outputs.TenantsTableName
        CustomersTableName: !GetAtt TablesStack.Outputs.CustomersTableName
        FleetsTableName: !GetAtt TablesStack.Outputs.FleetsTableName
        VehiclesTableName: !GetAtt TablesStack.Outputs.VehiclesTableName
        DriversTableName: !GetAtt TablesStack.Outputs.DriversTableName
        DriverAssignmentsTableName: !GetAtt TablesStack.Outputs.DriverAssignmentsTableName
        AuditLogTableName: !GetAtt TablesStack.Outputs.AuditLogTableName
        IdempotencyTableName: !GetAtt TablesStack.Outputs.IdempotencyTableName
        VehicleStateTableName: !GetAtt TablesStack.Outputs.VehicleStateTableName
        TripsTableName: !GetAtt TablesStack.Outputs.TripsTableName
        TripSummaryTableName: !GetAtt TablesStack.Outputs.TripSummaryTableName
        PslCacheTableName: !GetAtt TablesStack.Outputs.PslCacheTableName
        OverspeedDedupeTableName: !GetAtt TablesStack.Outputs.OverspeedDedupeTableName
        EnableTenantFleetIndex: !Ref EnableTenantFleetIndex
        UserPoolId: !If [UseProvidedUserPoolId, !Ref UserPoolId, !GetAtt CognitoStack.Outputs.UserPoolId]
        IngressCodeS3Bucket: !Ref TemplateBucket
        IngressCodeS3Key: !Ref IngressCodeS3Key
        TelematicsProcessorCodeS3Bucket: !Ref TemplateBucket
        TelematicsProcessorCodeS3Key: !Ref TelematicsProcessorCodeS3Key
        PslEnricherCodeS3Bucket: !Ref TemplateBucket
        PslEnricherCodeS3Key: !Ref PslEnricherCodeS3Key
        OverspeedDetectorCodeS3Bucket: !Ref TemplateBucket
        OverspeedDetectorCodeS3Key: !Ref OverspeedDetectorCodeS3Key
        TripSummaryBuilderCodeS3Bucket: !Ref TemplateBucket
        TripSummaryBuilderCodeS3Key: !Ref TripSummaryBuilderCodeS3Key
        TripSummaryApiCodeS3Bucket: !Ref TemplateBucket
        TripSummaryApiCodeS3Key: !Ref TripSummaryApiCodeS3Key
        VehicleStateApiCodeS3Bucket: !Ref TemplateBucket
        VehicleStateApiCodeS3Key: !Ref VehicleStateApiCodeS3Key
        FleetTenancyApiCodeS3Bucket: !Ref TemplateBucket
        FleetTenancyApiCodeS3Key: !Ref FleetTenancyApiCodeS3Key
        CommonLayerS3Bucket: !Ref TemplateBucket
        CommonLayerS3Key: !Ref CommonLayerS3Key
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/lambdas.yaml

  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        TripSummaryApiFunctionArn: !GetAtt LambdasStack.Outputs.TripSummaryApiFunctionArn
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/trip_summary_api.yaml

  VehicleStateApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        VehicleStateApiFunctionArn: !GetAtt LambdasStack.Outputs.VehicleStateApiFunctionArn
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/vehicle_state_api.yaml

  FleetTenancyApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        FleetTenancyApiFunctionArn: !GetAtt LambdasStack.Outputs.FleetTenancyApiFunctionArn
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/fleet_tenancy_api.yaml

  IngestApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        IngressQueueArn: !GetAtt QueuesStack.Outputs.IngressQueueArn
        IngressQueueName: !GetAtt QueuesStack.Outputs.IngressQueueName
        IngressQueueUrl: !GetAtt QueuesStack.Outputs.IngressQueueUrl
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/ingest_api.yaml

  UiStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableUiStackCondition
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
        UiBucketName: !If [UseProvidedUiBucketName, !Ref UiBucketName, ""]
        UiPriceClass: !Ref UiPriceClass
        UiCustomDomainName: !Ref UiCustomDomainName
        UiAcmCertificateArn: !Ref UiAcmCertificateArn
        UiHostedZoneId: !Ref UiHostedZoneId
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/ui.yaml

Outputs:
  Env:
    Value: !Ref Env
  ProjectName:
    Value: !Ref ProjectName
  IngestApiInvokeUrl:
    Value: !GetAtt IngestApiStack.Outputs.IngestApiInvokeUrl
  IngestApiId:
    Value: !GetAtt IngestApiStack.Outputs.IngestApiId
  IngestApiStageName:
    Value: !GetAtt IngestApiStack.Outputs.IngestApiStageName
  IngestQueueUrl:
    Value: !GetAtt IngestApiStack.Outputs.IngestQueueUrl
  IngestUsagePlanNote:
    Value: !GetAtt IngestApiStack.Outputs.IngestUsagePlanNote
  ApiStackTemplateURL:
    Description: Trip summary API nested template URL
    Value: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/${TemplateVersion}/nested/trip_summary_api.yaml
  VehicleStateApiInvokeUrl:
    Value: !GetAtt VehicleStateApiStack.Outputs.InvokeUrl
  VehicleStateApiId:
    Value: !GetAtt VehicleStateApiStack.Outputs.RestApiId
  FleetTenancyApiInvokeUrl:
    Value: !GetAtt FleetTenancyApiStack.Outputs.InvokeUrl
  FleetTenancyApiId:
    Value: !GetAtt FleetTenancyApiStack.Outputs.RestApiId
  TemplateVersionUsed:
    Description: TemplateVersion used for nested stack TemplateURL paths
    Value: !Ref TemplateVersion
  TemplatePrefixUsed:
    Description: TemplatePrefix used for nested stack TemplateURL paths
    Value: !Ref TemplatePrefix
  UserPoolId:
    Value: !If [UseProvidedUserPoolId, !Ref UserPoolId, !GetAtt CognitoStack.Outputs.UserPoolId]
  UserPoolClientId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
  UiBucketName:
    Condition: EnableUiStackCondition
    Value: !GetAtt UiStack.Outputs.UiBucketName
  UiDistributionId:
    Condition: EnableUiStackCondition
    Value: !GetAtt UiStack.Outputs.UiDistributionId
  UiCloudFrontDomainName:
    Condition: EnableUiStackCondition
    Value: !GetAtt UiStack.Outputs.UiCloudFrontDomainName
  UiAppUrl:
    Condition: EnableUiStackCondition
    Value: !GetAtt UiStack.Outputs.UiAppUrl
