AWSTemplateFormatVersion: "2010-09-09"
Description: onpoint root stack

Parameters:
  Env:
    Type: String
    Default: dev
  ProjectName:
    Type: String
    Default: onpoint
  TemplateBucket:
    Type: String
  TemplatePrefix:
    Type: String

Resources:
  StreamsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/nested/streams.yaml

  QueuesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/nested/queues.yaml

  TablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/nested/tables.yaml

  LambdasStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/nested/lambdas.yaml

  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/nested/api.yaml

Outputs:
  Env:
    Value: !Ref Env
  ProjectName:
    Value: !Ref ProjectName
