AWSTemplateFormatVersion: "2010-09-09"
Description: Vehicle Registry table for tenant/fleet/vehicle mapping

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedPattern: "^[a-z0-9-]+$"
    Description: Environment name (e.g., dev, test, prod)

Resources:
  VehicleRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-vehicle-registry"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  VehicleRegistryTableName:
    Value: !Ref VehicleRegistryTable