openapi: 3.0.3
info:
  title: OnPoint Tenancy User Management API
  version: 1.0.0
  description: User management endpoints (may not be deployed in current API Gateway stage).
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: ayephswoa1
      region:
        default: us-east-1
      stage:
        default: dev
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /tenants/{tenantId}/users:
    post:
      summary: Create tenant user
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '201': { description: Created }
    get:
      summary: List tenant users
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /tenants/{tenantId}/users/{userId}:
    get:
      summary: Get tenant user
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    patch:
      summary: Patch tenant user
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
        - in: path
          name: userId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '200': { description: OK }
  /platform/tenants/{tenantId}/admins:
    post:
      summary: Create tenant admin
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '201': { description: Created }
