AWSTemplateFormatVersion: "2010-09-09"
Description: "HTTP API: POST /ingest -> SQS, GET /trips + /trips/{vin}/{tripId} -> Trip Summary API Lambda."

Parameters:
  HttpApiName: { Type: String }
  IngressQueueUrl: { Type: String }
  IngressQueueArn: { Type: String }
  TripSummaryApiLambdaArn: { Type: String }

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref HttpApiName
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["GET","POST","OPTIONS"]
        AllowHeaders: ["content-type","authorization"]

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: "$default"
      AutoDeploy: true

  ApiToSqsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: apigateway.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allow-sendmessage
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !Ref IngressQueueArn

  IngestIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationSubtype: SQS-SendMessage
      CredentialsArn: !GetAtt ApiToSqsRole.Arn
      PayloadFormatVersion: "1.0"
      RequestParameters:
        QueueUrl: !Ref IngressQueueUrl
        MessageBody: "$request.body"

  IngestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /ingest"
      Target: !Sub "integrations/${IngestIntegration}"

  TripsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref TripSummaryApiLambdaArn
      PayloadFormatVersion: "2.0"

  TripsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /trips"
      Target: !Sub "integrations/${TripsIntegration}"

  TripDetailRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /trips/{vin}/{tripId}"
      Target: !Sub "integrations/${TripsIntegration}"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TripSummaryApiLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*"

Outputs:
  HttpApiEndpoint:
    Value: !GetAtt HttpApi.ApiEndpoint
