AWSTemplateFormatVersion: "2010-09-09"
Description: onpoint cognito user pool and app client

Parameters:
  Env:
    Type: String
  ProjectName:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ProjectName}-${Env}-user-pool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: tenantId
          AttributeDataType: String
          Mutable: true
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      MfaConfiguration: "OFF"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${ProjectName}-${Env}-user-client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  PlatformAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: PlatformAdmin
      UserPoolId: !Ref UserPool

  TenantAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: TenantAdmin
      UserPoolId: !Ref UserPool

  FleetManagerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: FleetManager
      UserPoolId: !Ref UserPool

  DispatcherGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Dispatcher
      UserPoolId: !Ref UserPool

  ReadOnlyGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: ReadOnly
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
