AWSTemplateFormatVersion: "2010-09-09"
Description: Messaging stack - SQS queues (with DLQs) + Kinesis ingress stream.

Parameters:
  IngressQueueName:
    Type: String
  IngressDlqName:
    Type: String

  # PSL enrichment (queue + DLQ)
  PslEnricherQueueName:
    Type: String
  PslEnricherDlqName:
    Type: String

  # Trip summary builder async (queue + DLQ)
  TripSummaryQueueName:
    Type: String
  TripSummaryDlqName:
    Type: String

  IngressStreamName:
    Type: String
  StreamShardCount:
    Type: Number
    Default: 1

Resources:
  # -----------------------
  # Ingress SQS
  # -----------------------
  IngressDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IngressDlqName
      MessageRetentionPeriod: 1209600  # 14 days

  IngressQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref IngressQueueName
      VisibilityTimeout: 60
      MessageRetentionPeriod: 345600  # 4 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IngressDlq.Arn
        maxReceiveCount: 5

  # -----------------------
  # PSL enricher SQS
  # -----------------------
  PslEnricherDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref PslEnricherDlqName
      MessageRetentionPeriod: 1209600

  PslEnricherQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref PslEnricherQueueName
      VisibilityTimeout: 120
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PslEnricherDlq.Arn
        maxReceiveCount: 5

  # -----------------------
  # Trip summary async SQS
  # -----------------------
  TripSummaryDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref TripSummaryDlqName
      MessageRetentionPeriod: 1209600

  TripSummaryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref TripSummaryQueueName
      # Trip summary builder can take longer (query trip events, compute, write)
      VisibilityTimeout: 300
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TripSummaryDlq.Arn
        maxReceiveCount: 5

  # -----------------------
  # Kinesis ingress stream
  # -----------------------
  IngressStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref IngressStreamName
      ShardCount: !Ref StreamShardCount
      StreamModeDetails:
        StreamMode: PROVISIONED
      RetentionPeriodHours: 24

Outputs:
  IngressQueueUrl:
    Value: !Ref IngressQueue
  IngressQueueArn:
    Value: !GetAtt IngressQueue.Arn
  IngressDlqUrl:
    Value: !Ref IngressDlq
  IngressDlqArn:
    Value: !GetAtt IngressDlq.Arn

  PslEnricherQueueUrl:
    Value: !Ref PslEnricherQueue
  PslEnricherQueueArn:
    Value: !GetAtt PslEnricherQueue.Arn
  PslEnricherDlqUrl:
    Value: !Ref PslEnricherDlq
  PslEnricherDlqArn:
    Value: !GetAtt PslEnricherDlq.Arn

  TripSummaryQueueUrl:
    Value: !Ref TripSummaryQueue
  TripSummaryQueueArn:
    Value: !GetAtt TripSummaryQueue.Arn
  TripSummaryDlqUrl:
    Value: !Ref TripSummaryDlq
  TripSummaryDlqArn:
    Value: !GetAtt TripSummaryDlq.Arn

  IngressStreamNameOut:
    Value: !Ref IngressStreamName
  IngressStreamArnOut:
    Value: !GetAtt IngressStream.Arn
