AWSTemplateFormatVersion: "2010-09-09"
Description: >
  DynamoDB tables (PAY_PER_REQUEST, AWS-managed KMS, no GSIs).
  TTL enabled for telemetry-events + psl-cache + overspeed-dedupe + geofence-events using attribute "expiresAt".

Parameters:
  DynamoAwsManagedKmsKeyId:
    Type: String
    Default: alias/aws/dynamodb

  TelemetryEventsTableName: { Type: String }
  TripsTableName: { Type: String }
  TripSummaryTableName: { Type: String }
  PslCacheTableName: { Type: String }
  OverspeedDedupeTableName: { Type: String }
  VehicleStateTableName: { Type: String }

  VehicleRegistryTableName: { Type: String }
  FleetRegistryTableName: { Type: String }
  CustomerFleetMapTableName: { Type: String }
  CustomerRegistryTableName: { Type: String }

  GeoFenceDefinitionsTableName: { Type: String }
  GeoFenceAssignmentsTableName: { Type: String }
  GeoFenceStateTableName: { Type: String }
  GeoFenceEventsTableName: { Type: String }

Resources:
  TelemetryEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TelemetryEventsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }
      TimeToLiveSpecification: { AttributeName: expiresAt, Enabled: true }

  TripsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TripsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  TripSummaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TripSummaryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  PslCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PslCacheTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }
      TimeToLiveSpecification: { AttributeName: expiresAt, Enabled: true }

  OverspeedDedupeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref OverspeedDedupeTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }
      TimeToLiveSpecification: { AttributeName: expiresAt, Enabled: true }

  VehicleStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref VehicleStateTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  CustomerRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CustomerRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  FleetRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FleetRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  CustomerFleetMapTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CustomerFleetMapTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  VehicleRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref VehicleRegistryTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  GeoFenceDefinitionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceDefinitionsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  GeoFenceAssignmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceAssignmentsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  GeoFenceStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceStateTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }

  GeoFenceEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GeoFenceEventsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }
      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      SSESpecification: { SSEEnabled: true, SSEType: KMS, KMSMasterKeyId: !Ref DynamoAwsManagedKmsKeyId }
      TimeToLiveSpecification: { AttributeName: expiresAt, Enabled: true }

Outputs:
  TelemetryEventsTableNameOut: { Value: !Ref TelemetryEventsTableName }
  TripsTableNameOut: { Value: !Ref TripsTableName }
  TripSummaryTableNameOut: { Value: !Ref TripSummaryTableName }
