AWSTemplateFormatVersion: "2010-09-09"
Description: >
  OnPointAI Lambda functions + shared Python layer.
  Deployed as a nested stack to keep redeploys predictable.

Parameters:
  ArtifactBucket:
    Type: String

  # Shared layer artifact (zip) -> Lambda LayerVersion
  CommonPythonLayerS3Key:
    Type: String
    Default: layers/onpoint_common_layer.zip

  # Lambda code artifacts (zips)
  IngressLambdaS3Key:
    Type: String
    Default: lambda/onpoint-dev-ingress.zip
  TelematicsProcessorLambdaS3Key:
    Type: String
    Default: lambda/onpoint-dev-telematics-processor.zip
  PslEnricherLambdaS3Key:
    Type: String
    Default: lambda/onpoint-psl-enricher.zip
  OverspeedDetectorLambdaS3Key:
    Type: String
    Default: lambda/onpoint-overspeed-detector.zip
  TripSummaryBuilderLambdaS3Key:
    Type: String
    Default: lambda/onpoint-dev-trip-summary-builder.zip
  TripSummaryApiLambdaS3Key:
    Type: String
    Default: lambda/onpoint-trip-summary-api.zip

  IngressQueueArn:
    Type: String
  IngressQueueUrl:
    Type: String
  TripSummaryQueueArn:
    Type: String
  TripSummaryQueueUrl:
    Type: String
  IngressStreamArn:
    Type: String
  IngressStreamName:
    Type: String

  TelemetryEventsTableName:
    Type: String
  TripsTableName:
    Type: String
  TripSummaryTableName:
    Type: String
  PslCacheTableName:
    Type: String
  OverspeedDedupeTableName:
    Type: String
  VehicleStateTableName:
    Type: String
  VehicleRegistryTableName:
    Type: String
  FleetRegistryTableName:
    Type: String
  CustomerFleetMapTableName:
    Type: String
  CustomerRegistryTableName:
    Type: String

Resources:
  # ------------------------------------------------------------
  # Shared layer
  # ------------------------------------------------------------
  CommonPythonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: onpoint-common-python
      CompatibleRuntimes:
        - python3.12
        - python3.11
      Content:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref CommonPythonLayerS3Key
      Description: Shared utilities for envelope, validation, tenant resolution, logging

  # ------------------------------------------------------------
  # IAM roles
  # ------------------------------------------------------------
  IngressLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IngressKinesisPut
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecords
                  - kinesis:PutRecord
                Resource: !Ref IngressStreamArn
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !Ref IngressQueueArn

  TelematicsProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoWriteTelemetry
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TelemetryEventsTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TripsTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${VehicleStateTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${VehicleRegistryTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${FleetRegistryTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerFleetMapTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerRegistryTableName}"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Ref TripSummaryQueueArn
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListShards
                Resource: !Ref IngressStreamArn

  PslEnricherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PslCacheAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${PslCacheTableName}"

  OverspeedDetectorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: OverspeedDedupeAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OverspeedDedupeTableName}"

  TripSummaryBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TripSummaryTablesAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TelemetryEventsTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TripSummaryTableName}"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !Ref TripSummaryQueueArn

  TripSummaryApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TripSummaryRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TripSummaryTableName}"

  # ------------------------------------------------------------
  # Lambdas
  # ------------------------------------------------------------
  IngressLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-ingress
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt IngressLambdaRole.Arn
      Timeout: 30
      MemorySize: 512
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref IngressLambdaS3Key
      Environment:
        Variables:
          INGRESS_STREAM_NAME: !Ref IngressStreamName
          DEFAULT_DOMAIN: telematics
          ENVIRONMENT: dev
          PROJECT_NAME: onpoint

  IngressEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref IngressQueueArn
      FunctionName: !Ref IngressLambda
      BatchSize: 10
      Enabled: true

  TelematicsProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-telematics-processor
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt TelematicsProcessorRole.Arn
      Timeout: 60
      MemorySize: 1024
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TelematicsProcessorLambdaS3Key
      Environment:
        Variables:
          TELEMETRY_EVENTS_TABLE: !Ref TelemetryEventsTableName
          TRIPS_TABLE: !Ref TripsTableName
          VEHICLE_STATE_TABLE: !Ref VehicleStateTableName
          VEHICLE_REGISTRY_TABLE: !Ref VehicleRegistryTableName
          FLEET_REGISTRY_TABLE: !Ref FleetRegistryTableName
          CUSTOMER_FLEET_MAP_TABLE: !Ref CustomerFleetMapTableName
          CUSTOMER_REGISTRY_TABLE: !Ref CustomerRegistryTableName
          TRIP_SUMMARY_QUEUE_URL: !Ref TripSummaryQueueUrl

  KinesisEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref IngressStreamArn
      FunctionName: !Ref TelematicsProcessorLambda
      StartingPosition: LATEST
      BatchSize: 100
      MaximumBatchingWindowInSeconds: 2
      Enabled: true

  PslEnricherLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-psl-enricher
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt PslEnricherRole.Arn
      Timeout: 30
      MemorySize: 512
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref PslEnricherLambdaS3Key
      Environment:
        Variables:
          PSL_CACHE_TABLE: !Ref PslCacheTableName
          ENVIRONMENT: dev
          PROJECT_NAME: onpoint

  OverspeedDetectorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-overspeed-detector
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt OverspeedDetectorRole.Arn
      Timeout: 30
      MemorySize: 512
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref OverspeedDetectorLambdaS3Key
      Environment:
        Variables:
          OVERSPEED_DEDUPE_TABLE: !Ref OverspeedDedupeTableName
          ENVIRONMENT: dev
          PROJECT_NAME: onpoint

  TripSummaryBuilderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-dev-trip-summary-builder
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt TripSummaryBuilderRole.Arn
      Timeout: 60
      MemorySize: 1024
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TripSummaryBuilderLambdaS3Key
      Environment:
        Variables:
          TELEMETRY_EVENTS_TABLE: !Ref TelemetryEventsTableName
          TRIP_SUMMARY_TABLE: !Ref TripSummaryTableName

  TripSummaryQueueEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref TripSummaryQueueArn
      FunctionName: !Ref TripSummaryBuilderLambda
      BatchSize: 10
      Enabled: true

  TripSummaryApiLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: onpoint-trip-summary-api
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt TripSummaryApiRole.Arn
      Timeout: 30
      MemorySize: 512
      Layers:
        - !Ref CommonPythonLayer
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref TripSummaryApiLambdaS3Key
      Environment:
        Variables:
          TRIP_SUMMARY_TABLE: !Ref TripSummaryTableName
          DEFAULT_LIMIT: "50"
          MAX_LIMIT: "200"

Outputs:
  CommonPythonLayerArn:
    Value: !Ref CommonPythonLayer

  IngressLambdaArn:
    Value: !GetAtt IngressLambda.Arn

  TelematicsProcessorLambdaArn:
    Value: !GetAtt TelematicsProcessorLambda.Arn

  PslEnricherLambdaArn:
    Value: !GetAtt PslEnricherLambda.Arn

  OverspeedDetectorLambdaArn:
    Value: !GetAtt OverspeedDetectorLambda.Arn

  TripSummaryBuilderLambdaArn:
    Value: !GetAtt TripSummaryBuilderLambda.Arn

  TripSummaryApiLambdaArn:
    Value: !GetAtt TripSummaryApiLambda.Arn
