AWSTemplateFormatVersion: "2010-09-09"
Description: >
  OnPointAI v4 (nested) - HTTP API -> SQS -> Ingress Lambda -> Kinesis -> Telematics Processor Lambda -> DynamoDB.
  Includes Trip Summary API + Trip Summary Builder (SQS). Also deploys PSL Enricher + Overspeed Detector as standalone
  lambdas (not wired to triggers by default) so you can integrate later without invasive changes.
  Cost-conscious defaults: PAY_PER_REQUEST tables, minimal logging, no GSIs.

Parameters:
  ProjectName:
    Type: String
    Default: onpoint
  Env:
    Type: String
    Default: dev

  # --- Artifact bucket/keys ---
  # This bucket must contain:
  #   (1) nested templates under templates/*
  #   (2) lambda zips under lambdas/*
  #   (3) optional layer zip under layers/*
  ArtifactBucket:
    Type: String
    Description: S3 bucket that contains Lambda zip artifacts AND nested templates.

  # Common python layer (onpoint_common). Optional but recommended.
  CommonPythonLayerS3Key:
    Type: String
    Default: layers/onpoint-common-layer.zip

  # Lambda zips
  IngressLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-dev-ingress.zip
  TelematicsProcessorLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-dev-telematics-processor.zip
  PslEnricherLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-psl-enricher.zip
  OverspeedDetectorLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-overspeed-detector.zip
  TripSummaryBuilderLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-dev-trip-summary-builder.zip
  TripSummaryApiLambdaS3Key:
    Type: String
    Default: lambdas/onpoint-trip-summary-api.zip

  # --- DynamoDB table names ---
  TelemetryEventsTableName:
    Type: String
    Default: onpoint-dev-telemetry-events
  TripsTableName:
    Type: String
    Default: onpoint-dev-trips
  TripSummaryTableName:
    Type: String
    Default: onpoint-dev-trip-summary
  PslCacheTableName:
    Type: String
    Default: onpoint-dev-psl-cache
  OverspeedDedupeTableName:
    Type: String
    Default: onpoint-dev-overspeed-dedupe
  VehicleStateTableName:
    Type: String
    Default: onpoint-dev-vehicle-state
  VehicleRegistryTableName:
    Type: String
    Default: dev-vehicle-registry
  FleetRegistryTableName:
    Type: String
    Default: onpoint-dev-fleet-registry
  CustomerFleetMapTableName:
    Type: String
    Default: onpoint-dev-customer-fleet-map
  CustomerRegistryTableName:
    Type: String
    Default: onpoint-dev-customer-registry

  # --- Geo-fence tables (created, lambdas not included yet) ---
  GeoFenceDefinitionsTableName:
    Type: String
    Default: onpoint-dev-geofence-definitions
  GeoFenceAssignmentsTableName:
    Type: String
    Default: onpoint-dev-geofence-assignments
  GeoFenceStateTableName:
    Type: String
    Default: onpoint-dev-geofence-state
  GeoFenceEventsTableName:
    Type: String
    Default: onpoint-dev-geofence-events

  # --- Messaging names ---
  IngressQueueName:
    Type: String
    Default: onpoint-dev-ingress-queue
  IngressDlqName:
    Type: String
    Default: onpoint-dev-ingress-dlq

  TripSummaryQueueName:
    Type: String
    Default: onpoint-dev-trip-summary-queue
  TripSummaryDlqName:
    Type: String
    Default: onpoint-dev-trip-summary-dlq

  IngressStreamName:
    Type: String
    Default: onpoint-dev-telematics
  IngressStreamShardCount:
    Type: Number
    Default: 2

  DynamoAwsManagedKmsKeyId:
    Type: String
    Default: alias/aws/dynamodb
    Description: AWS-managed KMS key for DynamoDB

  # --- API ---
  HttpApiName:
    Type: String
    Default: onpoint-dev-http-api

Resources:
  DynamoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactBucket}/templates/dynamodb.yaml"
      Parameters:
        DynamoAwsManagedKmsKeyId: !Ref DynamoAwsManagedKmsKeyId
        TelemetryEventsTableName: !Ref TelemetryEventsTableName
        TripsTableName: !Ref TripsTableName
        TripSummaryTableName: !Ref TripSummaryTableName
        PslCacheTableName: !Ref PslCacheTableName
        OverspeedDedupeTableName: !Ref OverspeedDedupeTableName
        VehicleStateTableName: !Ref VehicleStateTableName
        VehicleRegistryTableName: !Ref VehicleRegistryTableName
        FleetRegistryTableName: !Ref FleetRegistryTableName
        CustomerFleetMapTableName: !Ref CustomerFleetMapTableName
        CustomerRegistryTableName: !Ref CustomerRegistryTableName
        GeoFenceDefinitionsTableName: !Ref GeoFenceDefinitionsTableName
        GeoFenceAssignmentsTableName: !Ref GeoFenceAssignmentsTableName
        GeoFenceStateTableName: !Ref GeoFenceStateTableName
        GeoFenceEventsTableName: !Ref GeoFenceEventsTableName

  MessagingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactBucket}/templates/messaging.yaml"
      Parameters:
        IngressQueueName: !Ref IngressQueueName
        IngressDlqName: !Ref IngressDlqName
        TripSummaryQueueName: !Ref TripSummaryQueueName
        TripSummaryDlqName: !Ref TripSummaryDlqName
        IngressStreamName: !Ref IngressStreamName
        IngressStreamShardCount: !Ref IngressStreamShardCount

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DynamoStack
      - MessagingStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactBucket}/templates/lambdas.yaml"
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        CommonPythonLayerS3Key: !Ref CommonPythonLayerS3Key

        IngressLambdaS3Key: !Ref IngressLambdaS3Key
        TelematicsProcessorLambdaS3Key: !Ref TelematicsProcessorLambdaS3Key
        PslEnricherLambdaS3Key: !Ref PslEnricherLambdaS3Key
        OverspeedDetectorLambdaS3Key: !Ref OverspeedDetectorLambdaS3Key
        TripSummaryBuilderLambdaS3Key: !Ref TripSummaryBuilderLambdaS3Key
        TripSummaryApiLambdaS3Key: !Ref TripSummaryApiLambdaS3Key

        IngressQueueArn: !GetAtt MessagingStack.Outputs.IngressQueueArn
        IngressQueueUrl: !GetAtt MessagingStack.Outputs.IngressQueueUrl
        TripSummaryQueueArn: !GetAtt MessagingStack.Outputs.TripSummaryQueueArn
        TripSummaryQueueUrl: !GetAtt MessagingStack.Outputs.TripSummaryQueueUrl
        IngressStreamArn: !GetAtt MessagingStack.Outputs.IngressStreamArn
        IngressStreamName: !GetAtt MessagingStack.Outputs.IngressStreamName

        TelemetryEventsTableName: !Ref TelemetryEventsTableName
        TripsTableName: !Ref TripsTableName
        TripSummaryTableName: !Ref TripSummaryTableName
        PslCacheTableName: !Ref PslCacheTableName
        OverspeedDedupeTableName: !Ref OverspeedDedupeTableName
        VehicleStateTableName: !Ref VehicleStateTableName
        VehicleRegistryTableName: !Ref VehicleRegistryTableName
        FleetRegistryTableName: !Ref FleetRegistryTableName
        CustomerFleetMapTableName: !Ref CustomerFleetMapTableName
        CustomerRegistryTableName: !Ref CustomerRegistryTableName

  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - MessagingStack
      - LambdaStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactBucket}/templates/api.yaml"
      Parameters:
        HttpApiName: !Ref HttpApiName
        IngressQueueUrl: !GetAtt MessagingStack.Outputs.IngressQueueUrl
        IngressQueueArn: !GetAtt MessagingStack.Outputs.IngressQueueArn
        TripSummaryApiLambdaArn: !GetAtt LambdaStack.Outputs.TripSummaryApiLambdaArn

Outputs:
  HttpApiEndpoint:
    Value: !GetAtt ApiStack.Outputs.HttpApiEndpoint
  IngressQueueUrl:
    Value: !GetAtt MessagingStack.Outputs.IngressQueueUrl
  IngressStreamName:
    Value: !GetAtt MessagingStack.Outputs.IngressStreamName
  TripSummaryTableName:
    Value: !Ref TripSummaryTableName
  CommonPythonLayerArn:
    Value: !GetAtt LambdaStack.Outputs.CommonPythonLayerArn
  PslEnricherLambdaArn:
    Value: !GetAtt LambdaStack.Outputs.PslEnricherLambdaArn
  OverspeedDetectorLambdaArn:
    Value: !GetAtt LambdaStack.Outputs.OverspeedDetectorLambdaArn
